import 'dart:io';
import 'package:args/command_runner.dart';

import '../version.dart';
import 'commands/analyze_command.dart';
import 'commands/doctor_command.dart';
import 'commands/fix_command.dart';
import 'commands/generate_command.dart';
import 'commands/report_command.dart';
import 'commands/run_command.dart';
import 'project_service.dart';

class FlutterTestAiCommandRunner extends CommandRunner<int> {
  FlutterTestAiCommandRunner({ProjectService? service})
      : _service = service ?? ProjectService(),
        super(
          'fluttertest-ai',
          'Local-first Flutter test analysis and generation '
              '(no API key, no network).',
        ) {
    addCommand(DoctorCommand(service: _service));
    addCommand(AnalyzeCommand(service: _service));
    addCommand(GenerateCommand(service: _service));
    addCommand(RunCommand());
    addCommand(FixCommand());
    addCommand(ReportCommand(service: _service));
  }
  final ProjectService _service;

  @override
  Future<int> run(Iterable<String> args) async {
    if (args.contains('--version')) {
      print('FlutterTest AI v$packageVersion');
      return 0;
    }
    if (args.isEmpty || args.first == '--help' || args.first == '-h') {
      print('FlutterTest AI v$packageVersion\n');
    }
    try {
      final code = await super.run(args) ?? 0;
      if (args.isEmpty) {
        print(_usage);
        return 64;
      }
      return code;
    } on UsageException catch (error) {
      stderr.writeln(error);
      return 64;
    }
  }

  static const _usage = '''
Usage: fluttertest-ai <command> [path]

Commands:
  doctor    Verify Flutter, Dart, and the current project
  analyze   Analyze Dart files and print a conservative test plan
  generate  Generate tests only under test/
  run       Run only tests generated by FlutterTest AI
  fix       Apply safe deterministic repairs to generated tests
  report    Write JSON and Markdown reports under .fluttertest_ai/

Run `fluttertest-ai <command> --help` for command options.''';
}
