import 'package:path/path.dart' as p;

/// The ownership marker that identifies a test as generated by this tool.
const String generatedMarker = 'fluttertest_ai: generated';

/// Begin marker for the generated region of a test file.
const String generatedRegionBegin = 'fluttertest_ai: generated region begin';

/// End marker for the generated region of a test file.
const String generatedRegionEnd = 'fluttertest_ai: generated region end';

/// The two-line header required at the top of every generated test.
const String generatedHeader = '''
// Generated by FlutterTest AI.
// Review this test before using it in production.''';

/// Full ownership header including the confidence metadata for the file.
String generatedFileHeader(double confidence) => '''
$generatedHeader
// $generatedRegionBegin; confidence=${confidence.toStringAsFixed(2)}
''';

/// Builds the `package:<project>/<path>.dart` import URI for a lib/ file.
String packageImport(
    String sourcePath, String projectRoot, String projectName) {
  final relative = p.relative(sourcePath, from: p.join(projectRoot, 'lib'));
  final stem = p.withoutExtension(relative.replaceAll(r'\', '/'));
  return 'package:$projectName/$stem.dart';
}
