import 'dart:io';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:path/path.dart' as p;
import '../project/models.dart';

class WidgetTestGenerator {
  String? generate(TestPlanItem item, String projectName, String root,
      StateManagement state) {
    final unit = parseString(
            content: File(item.source).readAsStringSync(),
            path: item.source,
            throwIfDiagnostics: false)
        .unit;
    final candidates =
        unit.declarations.whereType<ClassDeclaration>().where((c) {
      final parent = c.extendsClause?.superclass.name.lexeme;
      if (!const {
        'StatelessWidget',
        'StatefulWidget',
        'ConsumerWidget',
        'HookWidget'
      }.contains(parent)) {
        return false;
      }
      final constructors =
          c.members.whereType<ConstructorDeclaration>().toList();
      ConstructorDeclaration? unnamed;
      for (final constructor in constructors) {
        if (constructor.name == null) {
          unnamed = constructor;
          break;
        }
      }
      return unnamed == null ||
          unnamed.parameters.parameters
              .where((p) => p.isRequiredNamed || p.isRequiredPositional)
              .isEmpty;
    }).toList();
    if (candidates.isEmpty) return null;
    final widget = candidates.first.name.lexeme;
    final import = p
        .withoutExtension(p.relative(item.source, from: p.join(root, 'lib')))
        .replaceAll(p.separator, '/');
    final riverpod = state == StateManagement.riverpod
        ? "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
        : '';
    final child = state == StateManagement.riverpod
        ? 'ProviderScope(child: MaterialApp(home: $widget()))'
        : 'MaterialApp(home: $widget())';
    return '''// Generated by FlutterTest AI.
// Review this test before using it in production.
// fluttertest_ai: generated; confidence=${item.confidence.toStringAsFixed(2)}

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
${riverpod}import 'package:$projectName/$import.dart';

void main() {
  testWidgets('$widget renders without crashing', (tester) async {
    await tester.pumpWidget($child);
    await tester.pump();
    expect(find.byType($widget), findsOneWidget);
  });
}
''';
  }
}
