import 'package:args/command_runner.dart';

import '../../execution/flutter_test_runner.dart';
import '../../reporting/console_reporter.dart';

class RunCommand extends Command<int> {
  RunCommand({FlutterTestRunner? runner})
      : _runner = runner ?? FlutterTestRunner();

  final FlutterTestRunner _runner;

  @override
  String get name => 'run';

  @override
  String get description =>
      'Run only the tests generated by FlutterTest AI through `flutter test`.';

  @override
  Future<int> run() async {
    final rest = argResults?.rest ?? const <String>[];
    final root = rest.isEmpty ? '.' : rest.first;
    final reporter = ConsoleReporter();
    reporter.banner();
    reporter.section('Running generated tests...');
    final result = await _runner.run(root);
    reporter.run(result);
    print('Report: ${result.reportPath}');
    return result.exitCode;
  }
}
