import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import 'package:fluttertest_ai/fluttertest_ai.dart';

void main() {
  final fixtures = p.join(Directory.current.path, 'test', 'fixtures');

  /// Creates a writable copy of a fixture in a temp directory.
  Directory fixtureCopy(String name) {
    final source = Directory(p.join(fixtures, name));
    final temp = Directory.systemTemp.createTempSync('fluttertest-ai-');
    addTearDown(() => temp.deleteSync(recursive: true));
    for (final entity in source.listSync(recursive: true)) {
      if (entity is! File) continue;
      final relative = p.relative(entity.path, from: source.path);
      final target = File(p.join(temp.path, relative))
        ..parent.createSync(recursive: true);
      target.writeAsStringSync(entity.readAsStringSync());
    }
    return temp;
  }

  test('generates unit tests for typed functions, utility classes, and '
      'state containers', () async {
    final root = fixtureCopy('provider_login');
    final analysis = await ProjectService().analyze(root.path);
    final plan = TestPlanBuilder().build(analysis, only: TestKind.unit);
    final result = await DartTestWriter().write(plan, analysis);
    expect(result.written, hasLength(1));
    final content =
        File(p.join(root.path, 'test', 'login_test.dart')).readAsStringSync();
    expect(content, contains('// Generated by FlutterTest AI.'));
    expect(content, contains('fluttertest_ai: generated'));
    expect(content, contains('EmailValidator().isValid'), reason: content);
    expect(content, contains('accepts typical input'));
    expect(content, contains('accepts empty input'));
    expect(content, contains('accepts null for nullable parameters'));
  });

  test('generates lifecycle and serialization tests for state classes',
      () async {
    final root = fixtureCopy('riverpod_async');
    final analysis = await ProjectService().analyze(root.path);
    final plan = TestPlanBuilder().build(analysis, only: TestKind.unit);
    final result = await DartTestWriter().write(plan, analysis);
    expect(result.written, hasLength(1));
    final content =
        File(p.join(root.path, 'test', 'home_test.dart')).readAsStringSync();
    expect(content, contains('UserModel.fromJson tolerates an empty map'));
    expect(content, contains('UserModelNotifier constructs and disposes'));
  });

  test('generates a widget harness with public UI signals', () async {
    final root = fixtureCopy('basic_set_state');
    final analysis = await ProjectService().analyze(root.path);
    final plan = TestPlanBuilder().build(analysis, only: TestKind.widget);
    final result = await DartTestWriter().write(plan, analysis);
    expect(result.written, hasLength(1));
    final content = File(p.join(root.path, 'test', 'main_widget_test.dart'))
        .readAsStringSync();
    expect(
        content, contains("import 'package:flutter_test/flutter_test.dart';"));
    expect(content, contains('MaterialApp(home: CounterScreen())'));
    expect(content, contains('testWidgets('));
    expect(content, contains("find.text('Count')"));
    expect(
        content, contains("find.byKey(const ValueKey('increment-button'))"));
    expect(content, contains('find.byType(ElevatedButton)'));
    expect(content, contains('// fluttertest_ai: generated region begin'));
  });

  test('never writes outside test/ and never touches lib/', () async {
    final root = fixtureCopy('basic_set_state');
    String libSnapshot() => Directory(p.join(root.path, 'lib'))
        .listSync(recursive: true)
        .map((entity) => entity is File ? entity.readAsStringSync() : '')
        .join();
    final before = libSnapshot();
    final analysis = await ProjectService().analyze(root.path);
    await DartTestWriter().write(TestPlanBuilder().build(analysis), analysis);
    expect(libSnapshot(), before);
    expect(
        Directory(p.join(root.path, 'test')).listSync(recursive: true),
        isNotEmpty);
  });

  test('handwritten tests are never overwritten, even with --force',
      () async {
    final root = fixtureCopy('basic_set_state');
    Directory(p.join(root.path, 'test')).createSync();
    final handwritten = File(p.join(root.path, 'test', 'main_widget_test.dart'))
      ..writeAsStringSync('// handwritten, do not touch');
    final analysis = await ProjectService().analyze(root.path);
    final result = await DartTestWriter().write(
      TestPlanBuilder().build(analysis, only: TestKind.widget),
      analysis,
      force: true,
    );
    expect(result.written, isEmpty);
    expect(result.skipped.join(' '), contains('handwritten test preserved'));
    expect(handwritten.readAsStringSync(), '// handwritten, do not touch');
  });

  test('--force refreshes only the generated region of a generated file',
      () async {
    final root = fixtureCopy('provider_login');
    final target = File(p.join(root.path, 'test', 'login_test.dart'))
      ..parent.createSync(recursive: true);
    const prefix = '// user note\n';
    target.writeAsStringSync('$prefix'
        '// fluttertest_ai: generated region begin; confidence=0.50\n'
        'void main() {}\n'
        '// fluttertest_ai: generated region end\n');
    final analysis = await ProjectService().analyze(root.path);
    final result = await DartTestWriter().write(
      TestPlanBuilder().build(analysis, only: TestKind.unit),
      analysis,
      force: true,
    );
    expect(result.written, hasLength(1));
    final content = target.readAsStringSync();
    expect(content.startsWith(prefix), isTrue, reason: content);
    expect(content, contains('EmailValidator'));
  });
}
